#Robocode Compiler Properties
#Wed Feb 07 11:53:50 CST 2024
robocode.version=1.9.4.7
compiler.binary=javac
compiler.options=-verbose -encoding UTF-8
compiler.classpath=-classpath libs\\robocode.jar;C\:\\Users\\King\\Documents\\GitHub\\robocode\\robots
